# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TesteiOSv2' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TesteiOSv2
     pod 'AlamofireObjectMapper', '~> 5.0'
     pod 'Alamofire', '~> 4.5'

  target 'TesteiOSv2Tests' do
    inherit! :search_paths
    # Pods for testing
     pod 'AlamofireObjectMapper', '~> 5.0'
     pod 'Alamofire', '~> 4.5'
  end

  target 'TesteiOSv2UITests' do
    inherit! :search_paths
    # Pods for testing
     pod 'AlamofireObjectMapper', '~> 5.0'
     pod 'Alamofire', '~> 4.5'
  end

end
